"""
Django settings for connect_liberia_backend project.
Generated by 'django-admin startproject' using Django 4.2.
For more information on this file, see:
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see:
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============= SECURITY =============
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-#)j-a5g)js7mue1mdo6t7x&aul(-0%cgjl1i@uh7v&)e98f3qy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allowed hosts - update for production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.railway.app,.vercel.app,.onrender.com').split(',')

# ============= APPLICATION DEFINITION =============
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'whitenoise.runserver_nostatic',
    # Email
    'anymail',  # For email notifications
    # 'storages',  # COMMENTED OUT - Using local storage
    # Local apps
    'api',
]

# ============= MIDDLEWARE =============
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============= URL CONFIG =============
ROOT_URLCONF = 'connect_liberia_backend.urls'

# ============= TEMPLATES =============
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'api' / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'connect_liberia_backend.wsgi.application'

# ============= DATABASE =============
# Use PostgreSQL in production, SQLite for local development
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=os.environ.get('DB_SSL', 'False') == 'True'
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ============= PASSWORD VALIDATION =============
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============= INTERNATIONALIZATION =============
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Monrovia'  # Liberia timezone
USE_I18N = True
USE_TZ = True

# ============= STATIC FILES =============
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============= MEDIA FILES - SUPABASE STORAGE =============
# Use Supabase Storage (free, persistent)
SUPABASE_URL = os.environ.get('SUPABASE_URL', 'https://pkuzqojtxxkkmfmmapzm.supabase.co')
SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdXpxb2p0eHhra21mbW1hcHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyNjcxOTQsImV4cCI6MjEwMjg0MzE5NH0.9xfDu3dzxhJGRoP_qSawBpFlN5nsemezUQEKmzaPUnc')

if SUPABASE_URL and SUPABASE_ANON_KEY:
    from api.supabase_storage import SupabaseStorage
    DEFAULT_FILE_STORAGE = 'api.supabase_storage.SupabaseStorage'
    MEDIA_URL = f"{SUPABASE_URL}/storage/v1/object/public/institutions/"
    MEDIA_ROOT = ''
else:
    # Fallback to local storage
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============= EMAIL CONFIGURATION =============
# Using SendGrid for email (free tier: 100 emails/day)
# Or use console for development

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Use SendGrid if API key is available, otherwise console
if os.environ.get('SENDGRID_API_KEY'):
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY')
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email settings
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Connect Liberia <noreply@connect-lib.onrender.com>')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'apikey')
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')

# Email templates configuration
EMAIL_TEMPLATES = {
    'welcome': 'emails/welcome.html',
    'password_reset': 'emails/password_reset.html',
    'suggestion_status': 'emails/suggestion_status.html',
    'newsletter': 'emails/newsletter.html',
}

# ============= DEFAULT AUTO FIELD =============
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============= CORS =============
# Allow all origins in development, restrict in production
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    CORS_ALLOWED_ORIGINS = [url for url in CORS_ALLOWED_ORIGINS if url]

# ============= ADD FRONTEND URLS TO CORS =============
# Explicitly add all frontend URLs
CORS_ALLOWED_ORIGINS += [
    "https://connect-liberia-website.vercel.app",
    "https://connect-liberia-admin.vercel.app",
    "https://connect-lib-1.onrender.com",
    "https://connect-liberia-website.onrender.com",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "https://connect-liberia-admin.vercel.app",
    "https://connect-lib-1.onrender.com",
    "https://connect-liberia-website.onrender.com",
    "https://connect-liberia-admin.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True

# Additional CORS headers
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============= JWT AUTHENTICATION =============
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============= REST FRAMEWORK =============
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============= SECURITY SETTINGS (Production) =============
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True') == 'True'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ============= LOGGING =============
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} - {levelname} - {name} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} - {levelname} - {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'WARNING'),
        },
        'api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# ============= AI / OPENROUTER CONFIGURATION =============
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

# ============= ANALYTICS =============
# Google Analytics (optional)
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID', '')

# ============= SITE CONFIGURATION =============
SITE_NAME = 'Connect Liberia'
SITE_URL = os.environ.get('SITE_URL', 'https://connect-lib-1.onrender.com')
SITE_DESCRIPTION = 'Making information about institutions across Liberia easily accessible to everyone.'

# ============= FRONTEND URLS =============
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://connect-lib-1.onrender.com')
ADMIN_FRONTEND_URL = os.environ.get('ADMIN_FRONTEND_URL', 'https://connect-liberia-admin.onrender.com')

# ============= PASSWORD RESET =============
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds