# Generated by Django 6.1 on 2026-08-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Name of the institution', max_length=255)),
                ('suggestion_type', models.CharField(choices=[('add', 'Add New Institution'), ('update', 'Update Existing Institution'), ('remove', 'Remove Institution')], max_length=20)),
                ('current_info', models.TextField(blank=True, help_text="What's currently shown (for updates)", null=True)),
                ('new_info', models.TextField(help_text='What should be added/changed')),
                ('suggester_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suggester_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('suggester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate Entry')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hospital', 'Hospital / Clinic'), ('school', 'School / University'), ('government', 'Government Office'), ('business', 'Business / Shop'), ('bank', 'Bank / Financial'), ('hotel', 'Hotel / Guesthouse'), ('ngo', 'NGO / Non-profit'), ('market', 'Market / Mall'), ('restaurant', 'Restaurant / Cafe'), ('church', 'Church / Mosque'), ('other', 'Other'), ('protected areas', 'Protected Areas'), ('park', 'Park')], max_length=50)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, help_text='List of services offered', null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('source', models.URLField(blank=True, help_text='Where this info was obtained', null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='api.county')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('update', 'Update'), ('event', 'Event'), ('alert', 'Alert'), ('general', 'General')], max_length=50)),
                ('source', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='api.county')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='api.institution')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['name'], name='api_institu_name_a1cf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['category'], name='api_institu_categor_2cab5f_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['county'], name='api_institu_county__4f21a0_idx'),
        ),
    ]
