# Generated by Django 6.1 on 2026-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_institution_average_rating_institution_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this news expires (auto-set to 48 hours)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to original article', null=True),
        ),
    ]
